[build][build]

builder = "DOCKERFILE"builder = "DOCKERFILE"

dockerfilePath = "Dockerfile"dockerfilePath = "Dockerfile"



[deploy][deploy]

startCommand = "php spark serve"startCommand = "apache2-foreground"

healthcheckPath = "/"healthcheckPath = "/"

restartPolicyType = "ON_FAILURE"restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3