[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/index.php"
healthcheckTimeout = 300
ports = [80]
startCommand = "apache2-foreground"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PHP_MEMORY_LIMIT = "512M"
PORT = "80"